### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by guoruibiao** [allen0125/DropKindle#2]
Dropbox这些外部存储内容同步到kindle是个好点子👍。
有些时候，看到一个网页，觉得还不赖，又没有时间去看，这种也是平时阅读的一个素材来源。

我之前只写了本地去手动输入链接，同步到kindle上的脚本，现在看起来，完全可以做成自动化的，对每天的链接分类输出，制作成一个PDF文档，再同步到kindle...

**Comment by allen0125** [comment]
其实我是觉得Kindle看PDF很费力的，并且认为网页稍后阅读用Pocket会特别合适。

然后，这个小Side Project重启了，欢迎PR🤣
