### ISSUE TITLE
兄dei，限制了一个用户吗？

### ISSUE THREAD

**Issue by happyjosh** [allen0125/DropKindle#3]
授权的时候报这个错误了
This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

**Comment by happyjosh** [comment]
授权的时候报这个错误了

**Comment by allen0125** [comment]
感谢，我正在做 Dropbox 第三方应用需要的 icon ，做完切换到生产环境就好了。

**Comment by allen0125** [comment]
应该是解决拉
